spring:
  main:
    allow-circular-references: true
  jackson:
    mapper:
      default-view-inclusion: true
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL94Dialect
      ddl-auto: validate
      default_batch_fetch_size: 20
      jdbc.batch_size: 20
      naming:
        #        implicit-strategy: org.hibernate.boot.model.naming.
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database: postgresql

    show-sql: true
    open-in-view: false

  datasource:
    url: jdbc:postgresql://localhost:5432/question-project
    username: postgres
    password: postgres
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-mastrer.xml
  data:
    mongodb:
      authentication-database: admin
      database: admin
      port: 27017
      host: localhost
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  shell:
    interactive:
      enabled: false
server:
  port: 9191
logging:
  level:
    - error

