CREATE TABLE IF NOT EXISTS public.answers
(
    ans_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    ans_name character varying(255) COLLATE pg_catalog."default",
    "ans_que_id" bigint NOT NULL,
    ans_check boolean NOT NULL,
    CONSTRAINT answers_pkey PRIMARY KEY (ans_id)
)
    WITH (
        OIDS = FALSE
    );