CREATE TABLE IF NOT EXISTS public.questions
(
    que_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    que_name character varying(255) COLLATE pg_catalog."default",
    num_of_corr bigint,
    que_lvl_id bigint NOT NULL,
    que_prof_id bigint NOT NULL,
    CONSTRAINT questions_pkey PRIMARY KEY (que_id)
    )
    WITH (
        OIDS = FALSE
        );

